"""
network/data_provider.py
────────────────────────
Capa de abstracción entre vistas y fuente de datos.

Las vistas NUNCA importan modelos directamente.
En su lugar usan:

    from network.data_provider import get_provider
    dp = get_provider()
    clientes = dp.clientes.get_all()

En modo LOCAL/SERVER → dp llama a los modelos con QSqlQuery (igual que antes).
En modo CLIENT       → dp hace requests HTTP al servidor Flask.

Esto permite que las vistas sean 100% idénticas en ambos modos.
"""
from __future__ import annotations
from typing import Optional, TYPE_CHECKING

# Importación lazy del modo actual
def _get_modo() -> str:
    try:
        from network.net_config import get_modo
        return get_modo()
    except Exception:
        return "local"


# ─── Singleton ───────────────────────────────────────────────────────────────

_provider_instance = None

def get_provider() -> "BaseProvider":
    """Retorna el provider singleton según el modo configurado."""
    global _provider_instance
    if _provider_instance is None:
        modo = _get_modo()
        if modo == "client":
            from network.http_client import HttpProvider
            _provider_instance = HttpProvider()
        else:
            from network.local_provider import LocalProvider
            _provider_instance = LocalProvider()
    return _provider_instance


def reset_provider() -> None:
    """Resetea el singleton (útil al cambiar de modo)."""
    global _provider_instance
    _provider_instance = None


# ─── Interfaces base (para type hints) ───────────────────────────────────────

class BaseClienteRepo:
    def get_all(self, solo_activos: bool = True): ...
    def get_by_id(self, id: int): ...
    def insertar(self, c) -> int: ...
    def actualizar(self, c) -> bool: ...
    def eliminar_logico(self, id: int) -> bool: ...
    def get_saldo_total(self, id: int) -> float: ...

class BasePedidoRepo:
    def generar_nro_pedido(self) -> str: ...
    def get_all(self, filtros=None): ...
    def get_by_id(self, id: int): ...
    def insertar(self, p) -> int: ...
    def actualizar(self, p) -> bool: ...
    def cambiar_estado(self, id: int, estado: str) -> bool: ...
    def get_stats_footer(self) -> dict: ...
    def get_por_estado(self, estados: list) -> list: ...

class BaseDetalleRepo:
    def get_by_pedido(self, pedido_id: int): ...
    def insertar(self, d) -> int: ...
    def actualizar(self, d) -> bool: ...
    def eliminar(self, id: int) -> bool: ...
    def eliminar_por_pedido(self, pedido_id: int) -> bool: ...

class BaseProductoRepo:
    def get_all(self, solo_activos: bool = True): ...
    def get_by_id(self, id: int): ...
    def insertar(self, p) -> int: ...
    def actualizar(self, p) -> bool: ...
    def eliminar_logico(self, id: int) -> bool: ...

class BaseTipoRepo:
    def get_all(self): ...
    def insertar(self, t) -> int: ...
    def actualizar(self, t) -> bool: ...
    def eliminar(self, id: int) -> bool: ...

class BasePagoRepo:
    def get_by_pedido(self, pedido_id: int): ...
    def insertar(self, p) -> int: ...
    def eliminar(self, id: int) -> bool: ...
    def get_total_pagado(self, pedido_id: int) -> float: ...

class BaseInsumoRepo:
    def get_all(self): ...
    def insertar(self, i) -> int: ...
    def actualizar(self, i) -> bool: ...
    def eliminar(self, id: int) -> bool: ...

class BaseConfigRepo:
    def get(self, clave: str, default: str = "") -> str: ...
    def set(self, clave: str, valor: str) -> bool: ...
    def esta_configurado(self) -> bool: ...
    def get_datos_imprenta(self) -> dict: ...
    def set_datos_imprenta(self, datos: dict) -> bool: ...

class BaseUsuarioRepo:
    def autenticar(self, username: str, password: str): ...
    def get_all(self): ...
    def insertar(self, u, password: str) -> int: ...
    def actualizar(self, u, nueva_password: str = "") -> bool: ...
    def guardar_recordar(self, username: str, recordar: bool): ...
    def get_usuario_recordado(self) -> Optional[str]: ...

class BaseFacturaRepo:
    def insertar(self, f) -> int: ...
    def actualizar_cae(self, id, nro, cae, vto, estado) -> bool: ...
    def marcar_email_enviado(self, id) -> bool: ...
    def get_by_pedido(self, pedido_id): ...
    def get_by_cliente(self, cliente_id): ...
    def get_by_id(self, id): ...

class BaseReciboRepo:
    def generar_nro(self) -> str: ...
    def insertar(self, r) -> int: ...
    def marcar_email(self, id) -> bool: ...
    def get_by_pedido(self, pedido_id): ...
    def get_by_cliente(self, cliente_id): ...

class BaseReporteRepo:
    def ventas_por_dia_mes(self, anio, mes): ...
    def balance_general(self) -> dict: ...
    def productos_mas_vendidos(self, anio, mes): ...
    def pedidos_cuenta_corriente(self, cliente_id): ...


class BaseProvider:
    """Interfaz del provider. Cada modo implementa esta clase."""
    clientes:  BaseClienteRepo
    pedidos:   BasePedidoRepo
    detalle:   BaseDetalleRepo
    productos: BaseProductoRepo
    tipos:     BaseTipoRepo
    pagos:     BasePagoRepo
    insumos:   BaseInsumoRepo
    config:    BaseConfigRepo
    usuarios:  BaseUsuarioRepo
    facturas:  BaseFacturaRepo
    recibos:   BaseReciboRepo
    reportes:  BaseReporteRepo
